services:
  db:
    image: mysql:8.0
    container_name: cafe-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: cafe-wp
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
    volumes:
      - ./themes/cafe-theme:/var/www/html/wp-content/themes/cafe-theme
      - ./themes/cafe-theme-sakura:/var/www/html/wp-content/themes/cafe-theme-sakura
      - wp_data:/var/www/html
volumes:
  db_data:
  wp_data:
